// <auto-generated />
using System;
using Area.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Area.Migrations
{
    [DbContext(typeof(AreaContext))]
    [Migration("20250426185531_v36")]
    partial class v36
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Area.Models.BugsReport", b =>
                {
                    b.Property<int>("Bug_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bug_Id"));

                    b.Property<string>("Bug_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskBugId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TestEmployee_id")
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Bug_Id");

                    b.HasIndex("TaskBugId");

                    b.HasIndex("TestEmployee_id");

                    b.ToTable("BugsReports");
                });

            modelBuilder.Entity("Area.Models.Evaluation", b =>
                {
                    b.Property<string>("EvaluationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BugsFixed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotiID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectEvaluationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<bool>("SubmittedOnTime")
                        .HasColumnType("bit");

                    b.Property<string>("TaskEvaluationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvaluationID");

                    b.HasIndex("NotiID")
                        .IsUnique()
                        .HasFilter("[NotiID] IS NOT NULL");

                    b.HasIndex("ProjectEvaluationID")
                        .IsUnique()
                        .HasFilter("[ProjectEvaluationID] IS NOT NULL");

                    b.HasIndex("TaskEvaluationID")
                        .IsUnique()
                        .HasFilter("[TaskEvaluationID] IS NOT NULL");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Area.Models.Graduation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NationalNumberId")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NationalNumberId");

                    b.ToTable("Graduation");
                });

            modelBuilder.Entity("Area.Models.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("Area.Models.Notification", b =>
                {
                    b.Property<string>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evaluatioid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaskID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("TaskID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Area.Models.Permission", b =>
                {
                    b.Property<string>("Permission_id")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Permission_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Permission_id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Permission_id = "1",
                            Permission_name = "Create Project"
                        },
                        new
                        {
                            Permission_id = "2",
                            Permission_name = "Edit Project"
                        },
                        new
                        {
                            Permission_id = "3",
                            Permission_name = "Delete Project"
                        },
                        new
                        {
                            Permission_id = "4",
                            Permission_name = "Create Task"
                        },
                        new
                        {
                            Permission_id = "5",
                            Permission_name = "Edit Task"
                        },
                        new
                        {
                            Permission_id = "6",
                            Permission_name = "Delete Task"
                        },
                        new
                        {
                            Permission_id = "7",
                            Permission_name = "Add Member"
                        },
                        new
                        {
                            Permission_id = "8",
                            Permission_name = "View Projects"
                        },
                        new
                        {
                            Permission_id = "9",
                            Permission_name = "View Tasks"
                        },
                        new
                        {
                            Permission_id = "10",
                            Permission_name = "View Reports"
                        },
                        new
                        {
                            Permission_id = "11",
                            Permission_name = "Test Tasks"
                        });
                });

            modelBuilder.Entity("Area.Models.Person", b =>
                {
                    b.Property<string>("NationalNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roleid")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("job")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalNumber");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Roleid");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Persons");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Area.Models.PersonNotification", b =>
                {
                    b.Property<string>("person_ID")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("notifi_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("person_ID", "notifi_ID");

                    b.HasIndex("notifi_ID");

                    b.ToTable("PersonNotifications");
                });

            modelBuilder.Entity("Area.Models.Project", b =>
                {
                    b.Property<string>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluatioProjectid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EvaluationScore")
                        .HasColumnType("float");

                    b.Property<string>("ManagerNationalNumber")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Product_Id")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionProjectDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SubmittedProjectOnTime")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.HasIndex("ManagerNationalNumber");

                    b.HasIndex("Product_Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Area.Models.Role", b =>
                {
                    b.Property<string>("Role_id")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Role_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Role_id = "1",
                            Role_name = "Manager"
                        },
                        new
                        {
                            Role_id = "2",
                            Role_name = "Product_Owner"
                        },
                        new
                        {
                            Role_id = "3",
                            Role_name = "Team_Leader"
                        },
                        new
                        {
                            Role_id = "4",
                            Role_name = "UI_Employee"
                        },
                        new
                        {
                            Role_id = "5",
                            Role_name = "Developer_Employee"
                        },
                        new
                        {
                            Role_id = "6",
                            Role_name = "Test_Employee"
                        });
                });

            modelBuilder.Entity("Area.Models.RolePermission", b =>
                {
                    b.Property<string>("Role_id")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Permission_id")
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Role_id", "Permission_id");

                    b.HasIndex("Permission_id");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Role_id = "1",
                            Permission_id = "1"
                        },
                        new
                        {
                            Role_id = "1",
                            Permission_id = "2"
                        },
                        new
                        {
                            Role_id = "1",
                            Permission_id = "3"
                        },
                        new
                        {
                            Role_id = "1",
                            Permission_id = "7"
                        },
                        new
                        {
                            Role_id = "1",
                            Permission_id = "8"
                        },
                        new
                        {
                            Role_id = "1",
                            Permission_id = "10"
                        },
                        new
                        {
                            Role_id = "2",
                            Permission_id = "4"
                        },
                        new
                        {
                            Role_id = "2",
                            Permission_id = "5"
                        },
                        new
                        {
                            Role_id = "3",
                            Permission_id = "4"
                        },
                        new
                        {
                            Role_id = "4",
                            Permission_id = "9"
                        },
                        new
                        {
                            Role_id = "5",
                            Permission_id = "9"
                        },
                        new
                        {
                            Role_id = "6",
                            Permission_id = "11"
                        });
                });

            modelBuilder.Entity("Area.Models.Task", b =>
                {
                    b.Property<string>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Developer_EmployeeId")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Developer_Employee_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evaluatiotasknid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leader_Id")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("ParentTaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Product_Id")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Project_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionTaskOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamLeader_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_EmployeeId")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Test_Employee_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UI_UXId")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("UI_UX_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("Developer_EmployeeId");

                    b.HasIndex("Leader_Id");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("Product_Id");

                    b.HasIndex("Project_Id");

                    b.HasIndex("Test_EmployeeId");

                    b.HasIndex("UI_UXId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Area.Models.WorkIn", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("NationalNumberId")
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("WorkPlace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("NationalNumberId");

                    b.ToTable("WorkIn");
                });

            modelBuilder.Entity("Area.Models.Developer_Employee", b =>
                {
                    b.HasBaseType("Area.Models.Person");

                    b.HasDiscriminator().HasValue("Developer_Employee");
                });

            modelBuilder.Entity("Area.Models.Manager", b =>
                {
                    b.HasBaseType("Area.Models.Person");

                    b.HasDiscriminator().HasValue("Manager");

                    b.HasData(
                        new
                        {
                            NationalNumber = "12345678901234",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.ahmed@gmail.com",
                            FirstName = "Ali",
                            LastName = "Ahmed",
                            Location = "Cairo",
                            MobileNumber = "01012345678",
                            Nationality = "Egyptian",
                            Password = "AliAhmed123",
                            Roleid = "1",
                            UserName = "Ali Ahmed"
                        });
                });

            modelBuilder.Entity("Area.Models.ProductOwner", b =>
                {
                    b.HasBaseType("Area.Models.Person");

                    b.HasDiscriminator().HasValue("Product_Owner");
                });

            modelBuilder.Entity("Area.Models.TeamLeader", b =>
                {
                    b.HasBaseType("Area.Models.Person");

                    b.HasDiscriminator().HasValue("Team_Leader");
                });

            modelBuilder.Entity("Area.Models.Test_Employee", b =>
                {
                    b.HasBaseType("Area.Models.Person");

                    b.HasDiscriminator().HasValue("Test_Employee");
                });

            modelBuilder.Entity("Area.Models.UI_UX", b =>
                {
                    b.HasBaseType("Area.Models.Person");

                    b.HasDiscriminator().HasValue("UI_Employee");
                });

            modelBuilder.Entity("Area.Models.BugsReport", b =>
                {
                    b.HasOne("Area.Models.Task", "TaskBug")
                        .WithMany("bugsReports")
                        .HasForeignKey("TaskBugId");

                    b.HasOne("Area.Models.Test_Employee", "TestEmployeebug")
                        .WithMany("BugsDOReport")
                        .HasForeignKey("TestEmployee_id");

                    b.Navigation("TaskBug");

                    b.Navigation("TestEmployeebug");
                });

            modelBuilder.Entity("Area.Models.Evaluation", b =>
                {
                    b.HasOne("Area.Models.Notification", "Notifications")
                        .WithOne("Evaluations")
                        .HasForeignKey("Area.Models.Evaluation", "NotiID");

                    b.HasOne("Area.Models.Project", "ProjectEvaluation")
                        .WithOne("EvaluationProject")
                        .HasForeignKey("Area.Models.Evaluation", "ProjectEvaluationID");

                    b.HasOne("Area.Models.Task", "TaskEvaluation")
                        .WithOne("EvaluationTask")
                        .HasForeignKey("Area.Models.Evaluation", "TaskEvaluationID");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectEvaluation");

                    b.Navigation("TaskEvaluation");
                });

            modelBuilder.Entity("Area.Models.Graduation", b =>
                {
                    b.HasOne("Area.Models.Person", "Person")
                        .WithMany("graduations")
                        .HasForeignKey("NationalNumberId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Area.Models.Notification", b =>
                {
                    b.HasOne("Area.Models.Project", "Project")
                        .WithMany("Notifications")
                        .HasForeignKey("ProjectID");

                    b.HasOne("Area.Models.Task", "Task")
                        .WithMany("NotificationsTask")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Area.Models.Person", b =>
                {
                    b.HasOne("Area.Models.Role", "Role")
                        .WithMany("Persons")
                        .HasForeignKey("Roleid");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Area.Models.PersonNotification", b =>
                {
                    b.HasOne("Area.Models.Notification", "Notification")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("notifi_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Area.Models.Person", "Person")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("person_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Area.Models.Project", b =>
                {
                    b.HasOne("Area.Models.Manager", null)
                        .WithMany("Projects")
                        .HasForeignKey("ManagerNationalNumber");

                    b.HasOne("Area.Models.ProductOwner", "ProductOwner")
                        .WithMany("Projects")
                        .HasForeignKey("Product_Id");

                    b.Navigation("ProductOwner");
                });

            modelBuilder.Entity("Area.Models.RolePermission", b =>
                {
                    b.HasOne("Area.Models.Permission", "Permission")
                        .WithMany("RolePermission")
                        .HasForeignKey("Permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Area.Models.Role", "Role")
                        .WithMany("RolePermission")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Area.Models.Task", b =>
                {
                    b.HasOne("Area.Models.Developer_Employee", "Developer_Employee")
                        .WithMany("Developer_EmployeeTasks")
                        .HasForeignKey("Developer_EmployeeId")
                        .HasConstraintName("FK_Tasks_Persons_Developer_Employee_NationalNumber");

                    b.HasOne("Area.Models.TeamLeader", "TeamLeader")
                        .WithMany("TeamLeaderTasks")
                        .HasForeignKey("Leader_Id")
                        .HasConstraintName("FK_Tasks_Persons_TeamLeader_NationalNumber");

                    b.HasOne("Area.Models.Task", "ParentTask")
                        .WithMany()
                        .HasForeignKey("ParentTaskId");

                    b.HasOne("Area.Models.ProductOwner", "ProductOwner")
                        .WithMany("ProductTasks")
                        .HasForeignKey("Product_Id");

                    b.HasOne("Area.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("Project_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Area.Models.Test_Employee", "Test_Employee")
                        .WithMany("Test_EmployeeTasks")
                        .HasForeignKey("Test_EmployeeId")
                        .HasConstraintName("FK_Tasks_Persons_Test_Employee_NationalNumber");

                    b.HasOne("Area.Models.UI_UX", "UI_UX")
                        .WithMany("UI_EmployeeTasks")
                        .HasForeignKey("UI_UXId")
                        .HasConstraintName("FK_Tasks_Persons_UI_UX_NationalNumber");

                    b.Navigation("Developer_Employee");

                    b.Navigation("ParentTask");

                    b.Navigation("ProductOwner");

                    b.Navigation("Project");

                    b.Navigation("TeamLeader");

                    b.Navigation("Test_Employee");

                    b.Navigation("UI_UX");
                });

            modelBuilder.Entity("Area.Models.WorkIn", b =>
                {
                    b.HasOne("Area.Models.Person", "Person")
                        .WithMany("WorkPlaces")
                        .HasForeignKey("NationalNumberId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Area.Models.Notification", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("PersonNotifications");
                });

            modelBuilder.Entity("Area.Models.Permission", b =>
                {
                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("Area.Models.Person", b =>
                {
                    b.Navigation("PersonNotifications");

                    b.Navigation("WorkPlaces");

                    b.Navigation("graduations");
                });

            modelBuilder.Entity("Area.Models.Project", b =>
                {
                    b.Navigation("EvaluationProject");

                    b.Navigation("Notifications");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Area.Models.Role", b =>
                {
                    b.Navigation("Persons");

                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("Area.Models.Task", b =>
                {
                    b.Navigation("EvaluationTask");

                    b.Navigation("NotificationsTask");

                    b.Navigation("bugsReports");
                });

            modelBuilder.Entity("Area.Models.Developer_Employee", b =>
                {
                    b.Navigation("Developer_EmployeeTasks");
                });

            modelBuilder.Entity("Area.Models.Manager", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Area.Models.ProductOwner", b =>
                {
                    b.Navigation("ProductTasks");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Area.Models.TeamLeader", b =>
                {
                    b.Navigation("TeamLeaderTasks");
                });

            modelBuilder.Entity("Area.Models.Test_Employee", b =>
                {
                    b.Navigation("BugsDOReport");

                    b.Navigation("Test_EmployeeTasks");
                });

            modelBuilder.Entity("Area.Models.UI_UX", b =>
                {
                    b.Navigation("UI_EmployeeTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
